### ISSUE TITLE
Bad formatting in chrome

### ISSUE THREAD

**Issue by Marviel** [0xreeko/gpt2markdown#11]
<img width="875" alt="Screen Shot 2023-03-15 at 8 34 21 PM" src="https://user-images.githubusercontent.com/2037165/225479091-0665b128-54dd-4e44-834d-3fe7deaaa706.png">

**Comment by phugadev** [comment]
thanks for the issue! pushing a new update in a couple 🫡

**Comment by phugadev** [comment]
the update was pushed - could you let me know if this was solved on your end?
