### ISSUE TITLE
Put a link of the web extension in the Github project

### ISSUE THREAD

**Issue by juan7732** [0xreeko/gpt2markdown#7]
![image](https://user-images.githubusercontent.com/19902389/220112615-88b83b98-a6ca-450a-94f0-94c84608d983.png)

It's good to push users to the chrome extension :D

**Comment by phugadev** [comment]
<img width="320" alt="Screenshot" src="https://user-images.githubusercontent.com/35407606/223062778-53d8219c-06f5-4547-b22f-88bd27d605c5.png">

thanks Juan! Just added the link!
