### ISSUE TITLE
Attribution causes flex box issues when using ChatGPT+

### ISSUE THREAD

**Issue by juan7732** [0xreeko/gpt2markdown#8]
Current:
![image](https://user-images.githubusercontent.com/19902389/220112925-be8091ae-f963-4e14-98a3-c159e6f09caf.png)

Better:
![image](https://user-images.githubusercontent.com/19902389/220113014-2c9bc518-ce4c-483b-b5fd-b7db973d75de.png)

I know this isn't great because you're losing some attribution here to your socials.

I recommend either having this as a tooltip pop up if possible, or maybe removing a little to fit better.

**Comment by SuperGNUS** [comment]
I just ran into this as well and would appreciate a fix!
